name: Create Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create Release on Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Define version variable
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/} | tr '.' '_')" >> $GITHUB_ENV

      - name: Create ZIP of repository (excluding .git, .github, and sample_data)
        run: |
          zip -r "lapeliculera_${VERSION}.zip" . -x ".git/*" ".github/*" "sample_data/*"

      - name: Create ZIP of sample_data
        run: |
          if [ -d "sample_data" ]; then
            zip -r sample_data.zip sample_data
          fi

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            lapeliculera_${{ env.VERSION }}.zip
            sample_data.zip
