name: Create Release On Tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create Release On Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Define version variable
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Remove existing ZIPs
        run: rm -f La_Peliculera_*.zip La_Peliculera_Docker_*.zip sample_data.zip

      - name: Create ZIP of La Peliculera (portable Odoo version)
        run: |
          zip -qr "La_Peliculera_${VERSION}.zip" addons/lapeliculera

      - name: Create ZIP of La Peliculera (Docker version)
        run: |
          zip -qr "La_Peliculera_Docker_${VERSION}.zip" . -x ".git/**" ".github/**" ".gitignore" "addons/lapeliculera/sample_data/**"
          
      - name: Create ZIP of sample_data (always)
        run: zip -qr sample_data.zip addons/lapeliculera/sample_data || echo "No sample_data folder, but zip created"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: La Peliculera ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            La_Peliculera_${{ env.VERSION }}.zip
            La_Peliculera_Docker_${{ env.VERSION }}.zip
            sample_data.zip
